"""empty message

Revision ID: bf32b9b34b4
Revises: 3c755431b519
Create Date: 2013-11-23 01:10:55.986000

"""

# revision identifiers, used by Alembic.
revision = 'bf32b9b34b4'
down_revision = '3c755431b519'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
